# Generated by Django 5.1.5 on 2025-04-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_username', models.CharField(max_length=200)),
                ('customer_password', models.CharField(max_length=200, unique=True)),
                ('customer_city', models.CharField(max_length=200)),
                ('customer_mobile', models.CharField(max_length=200, unique=True)),
                ('customer_email', models.EmailField(max_length=200, unique=True)),
                ('last_login', models.DateTimeField(default=0, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vehicle_name', models.CharField(max_length=100)),
                ('vehicle_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
