# Generated by Django 5.1.5 on 2025-04-15 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('driver_name', models.CharField(max_length=200)),
                ('driver_username', models.CharField(max_length=200)),
                ('driver_password', models.CharField(max_length=200, unique=True)),
                ('driver_city', models.CharField(max_length=200)),
                ('driver_mobile', models.CharField(max_length=200, unique=True)),
                ('driver_email', models.EmailField(max_length=200, unique=True)),
                ('driver_vehicle', models.CharField(choices=[('auto', 'auto'), ('car', 'car'), ('bike', 'bike')], max_length=200)),
                ('driver_licence', models.CharField(default=0, max_length=200, unique=True)),
                ('last_login', models.DateTimeField(default=0, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('available', 'available'), ('ride', 'ride'), ('active', 'active')], default='available', max_length=200)),
                ('is_login', models.BooleanField(default=False)),
                ('vehicles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend_1.vehicle')),
            ],
        ),
    ]
