# Generated by Django 5.1.5 on 2025-04-15 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_1', '0003_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('feedback_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('driver_id', models.IntegerField()),
                ('traveler_id', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(max_length=500)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend_1.booking')),
            ],
        ),
    ]
