# Generated by Django 5.1.5 on 2025-04-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_1', '0004_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_login',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='driver',
            name='last_login',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
