# Generated by Django 5.1.5 on 2025-04-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_1', '0005_alter_customer_last_login_alter_driver_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='is_login',
            field=models.BooleanField(default=True),
        ),
    ]
