# Generated by Django 5.1.5 on 2025-04-20 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_1', '0007_alter_feedback_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='is_login',
        ),
    ]
