# Generated by Django 5.1.5 on 2025-04-21 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_1', '0008_remove_driver_is_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('cash', 'cash'), ('gpay', 'gpay')], max_length=200)),
                ('amount', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend_1.booking')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend_1.driver')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend_1.customer')),
            ],
        ),
    ]
