
from django.urls import path
from . import views

urlpatterns = [
    path("",views.home),
    path("home",views.home),
    path("about us",views.about),
    path("safety",views.safety),
    path("careers",views.careers),
    path("contact",views.contact),
    path("login/sign/signup_customer/",views.signup_traveller),
    path("login/sign/signup_customer/getSignupTraveller",views.getSignupTraveller),
    path("login/sign/signup_driver/",views.signup_driver),
    path("login/sign/signup_driver/getSignupDriver",views.getSignupDriver),
    path("login/",views.login),
    path("login/sign/",views.sign),
    path("login/login_check",views.login_check),
    path("booking/logout",views.logout),
    path("booking/",views.booking),
    path("login/forget",views.forget),
    path("driver_login",views.login_driver),
    path("driver_login/driver_login_check",views.login_driver_check),
    path("sign/",views.sign),
    path("sign/signup_customer/",views.signup_traveller),
    path("sign/signup_customer/getSignupTraveller",views.getSignupTraveller),
    path("sign/signup_driver/",views.signup_driver),
    path("sign/signup_driver/getSignupDriver",views.getSignupDriver),
    path("login/changepassword",views.change_password),
    path("forget/",views.forget),
    path("forget/changepassword",views.change_password_driver),
    path("driver_booking/",views.driver_booking),
    path("booking/bookingDetails/<int:vehicle_id>/<str:fare>/<str:source>/<str:dest>/",views.booking_details, name = 'bookingDetail'),
    path("booking/profile/",views.profile),
    path("booking/profile/editProfile/",views.edit_profile),
    path("booking/profile/editProfile/profile_edit",views.profile_edit),
    path("booking/profile/profile",views.profile),
    path("booking/profile/logout",views.logout),
    path("driver_booking/logout",views.logout),
    path("driver_booking/profile/",views.driver_profile),
    path("driver_booking/profile/editProfile/",views.driver_edit_profile),
    path("driver_booking/profile/editProfile/driver_profile_edit",views.driver_edit_profile_change),
    path("booking/bookingDetails/<int:vehicle_id>/<str:fare>/<str:source>/<str:dest>/booking_status/",views.booking_status),
    path("driver_booking/accept/<int:booking_id>/<int:driver_id>",views.accept,name="accept"),
    path("driver_booking/delete/<int:booking_id>/<int:driver_id>",views.delete, name="delete"),
    path("booking/bookingDetails/booking_status/delete/<int:booking_id>/",views.delete_traveler, name="delete_traveler"),
    path("driver_booking/complete/<int:booking_id>/",views.complete,name = "driver_complete"),
    path("booking/bookingDetails/booking_status/update/<int:booking_id>/",views.payment_traveler, name="payment_traveler"),
    path("driver_booking/driver_history/",views.driver_history),
    path("driver_booking/driver_history/profile",views.driver_profile),
    path("driver_booking/driver_history/driver_history/",views.driver_history),
    path("driver_booking/driver_history/logout/",views.logout),
    path("driver_booking/profile/logout/",views.logout),
    path("booking/logout",views.logout),
    path("booking/driver_history/",views.driver_history),
    path("booking/bookingDetails/booking_status/update/payment/<int:booking_id>/",views.payment, name="cash"),
    path("booking/bookingDetails/booking_status/update/gpay/<int:booking_id>/",views.Gpay, name="gpay"),
    path("booking/bookingDetails/booking_status/update/gpay/payment_confirm/<int:booking_id>/",views.payment_confirmation, name="payment_confirm"),
    path("booking/bookingDetails/booking_status/update/gpay/payment_confirm/complete/<int:booking_id>/",views.payment_complete, name="payment_complete"),
    path("booking/bookingDetails/booking_status/update/payment/feedback/<int:booking_id>/",views.Feedback, name="feedback"),
    
]
